name: pytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.18

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests with coverage
        run: >
          python -m pytest resources/home/dnanexus/tests/test_make_workbook.py
          --cov=resources/home/dnanexus
          --cov-report=term-missing
          --cov-report=xml

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage.xml
          language: Python
          label: code-coverage/pytest